// packages/vue/vue-convolver-player/src/components/ConvolverPlayer.vue
<template>
  <div class="convolver-player">
    <div class="convolver-examples">
      <button
        v-for="sound in testSounds"
        :key="sound.label"
        :disabled="!irBuffer"
        @click="playTestSound(sound)"
      >
        <i class="lni lni-play"></i>
        {{ sound.label }}
      </button>
    </div>
    <div class="convolver-ir">
      <span v-if="irBuffer" class="convolver-ir-info">
        Duration: {{ irBuffer.duration.toFixed(2) }}s, Sample Rate:
        {{ irBuffer.sampleRate }}Hz, Channels: {{ irBuffer.numberOfChannels }}
      </span>
      <span v-else>Loading IR...</span>
      <canvas ref="waveformCanvas" class="convolver-waveform-canvas"></canvas>
      <div class="convolver-controls">
        <label for="wet-gain">Effect:</label>
        <input
          id="wet-gain"
          v-model="wetGainValue"
          type="range"
          min="0"
          max="1"
          step="0.01"
          :style="`--value: ${Math.round(wetGainValue * 100)}%`"
        />
        <span key="wet-gain-display-key">{{ displayedWetGain }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, onBeforeUnmount, computed } from "vue";
import {
  loadAudioBuffer,
  ConvolverProcessor,
  drawWaveform,
  setupCanvasContext,
  getAccentColor,
} from "@convolver-player/core";
import type { TestSound, Props } from "../types";

const props = defineProps<Props>();

let convolverProcessor: ConvolverProcessor | null = null;

const localAudioContext = ref<AudioContext | null>(null);

const irBuffer = ref<AudioBuffer | null>(null);
const waveformCanvas = ref<HTMLCanvasElement | null>(null);
const ctx = ref<CanvasRenderingContext2D | null>(null);
let rafId: number | null = null;

const wetGainValue = ref<number>(1); // Initial wet gain value (100% wet)

const displayedWetGain = computed<string>(() => {
  return String((wetGainValue.value * 100).toFixed(0)) + "%";
});

import click from "../assets/sounds/click.wav";
import piano from "../assets/sounds/piano.wav";
import guitar from "../assets/sounds/guitar.wav";
import snare from "../assets/sounds/snare.wav";

const testSounds: TestSound[] = [
  { label: "Click", type: "sample", path: click },
  { label: "Piano", type: "sample", path: piano },
  { label: "Guitar", type: "sample", path: guitar },
  { label: "Snare", type: "sample", path: snare },
];

// Function to load the IR
const loadIR = async (path: string, audioContext: AudioContext) => {
  try {
    irBuffer.value = await loadAudioBuffer(audioContext, path);
    setupCanvasAndDraw();
  } catch (error) {
    console.error("Error loading IR:", error);
    irBuffer.value = null;
  }
};

// Function to generate and play a test sound through the IR
const playTestSound = async (soundConfig: TestSound) => {
  const audioContext = props.audioContext || localAudioContext.value;

  if (!audioContext || !convolverProcessor) {
    console.warn("AudioContext or ConvolverProcessor not initialized.");
    return;
  }

  // Resume audio context if it's suspended (e.g., due to browser autoplay policies)
  if (audioContext.state === 'suspended') {
    await audioContext.resume();
  }

  if (!irBuffer.value) {
    console.warn("IR not ready.");
    return;
  }

  try {
    const testBuffer = await loadAudioBuffer(audioContext, soundConfig.path);
    await convolverProcessor.play(testBuffer);
  } catch (error) {
    console.error("Error playing test sound:", error);
  }
};

const setupCanvasAndDraw = () => {
  if (!waveformCanvas.value || !irBuffer.value) return;

  const canvas = waveformCanvas.value;
  const context = setupCanvasContext(canvas);
  if (!context) return;
  ctx.value = context;

  const color = getAccentColor(canvas);
  drawWaveform(ctx.value, irBuffer.value, canvas.width / (window.devicePixelRatio || 1), canvas.height / (window.devicePixelRatio || 1), color);
};

watch(
  () => props.irFilePath,
  async (newPath) => {
    const audioContext = props.audioContext || localAudioContext.value;

    if (!audioContext) return;

    if (newPath) {
      await loadIR(newPath, audioContext);
      if (irBuffer.value) {
        if (convolverProcessor) {
          convolverProcessor.updateIrBuffer(irBuffer.value); // Call updateIrBuffer
        } else {
          convolverProcessor = new ConvolverProcessor({ // Initialize if not exists
            audioContext: audioContext,
            irBuffer: irBuffer.value,
            wetGainValue: wetGainValue.value, // Pass wetGainValue
          });
        }
      }
    } else {
      irBuffer.value = null;
      if (ctx.value && waveformCanvas.value) {
        ctx.value.clearRect(
          0,
          0,
          waveformCanvas.value.width,
          waveformCanvas.value.height
        );
      }
    }
  },
  { immediate: true }
);



watch(irBuffer, () => {
  if (rafId) {
    window.cancelAnimationFrame(rafId);
  }
  rafId = window.requestAnimationFrame(setupCanvasAndDraw);
});

watch(wetGainValue, (newValue: number) => {
  if (convolverProcessor) {
    convolverProcessor.setWetDryMix(newValue);
  }
});

let resizeObserver: ResizeObserver | null = null;

onMounted(async () => {
  let audioContext: AudioContext;
  if (props.audioContext) {
    audioContext = props.audioContext;
  } else {
    localAudioContext.value = new AudioContext();
    audioContext = localAudioContext.value;
  }

  if (!audioContext) {
    console.error("AudioContext is not supported in this browser.");
    return;
  }
  // Resume audio context if it's suspended (e.g., due to browser autoplay policies)
  if (audioContext.state === 'suspended') {
    await audioContext.resume();
  }

  // Initialize convolverProcessor here if irFilePath is already set
  if (props.irFilePath && !convolverProcessor) {
    await loadIR(props.irFilePath, audioContext); // Load IR first
    if (irBuffer.value) {
      convolverProcessor = new ConvolverProcessor({
        audioContext: audioContext,
        irBuffer: irBuffer.value,
        wetGainValue: wetGainValue.value,
      });
    }
  }

  resizeObserver = new ResizeObserver(() => {
    if (rafId) {
      window.cancelAnimationFrame(rafId);
    }
    rafId = window.requestAnimationFrame(setupCanvasAndDraw);
  });

  if (waveformCanvas.value && waveformCanvas.value.parentElement) {
    resizeObserver.observe(waveformCanvas.value.parentElement);
  }
});

onBeforeUnmount(() => {
  if (resizeObserver) {
    resizeObserver.disconnect();
  }
  if (rafId) {
    window.cancelAnimationFrame(rafId);
  }
  if (convolverProcessor) {
    convolverProcessor.dispose();
  }
  if (localAudioContext.value) { // Check if local context exists
    localAudioContext.value.close(); // Close local context
  }
});
</script>

// packages/react/react-convolver-player/src/components/ConvolverPlayer.tsx
import React, { useRef, useEffect, useState, useCallback } from 'react';
import {
  ConvolverProcessor,
  loadAudioBuffer,
  drawWaveform,
  setupCanvasContext,
  getAccentColor,
} from '@convolver-player/core';
import type { TestSound, ConvolverPlayerProps } from '@convolver-player/core/types';

import clickSound from '../assets/sounds/click.wav';
import guitarSound from '../assets/sounds/guitar.wav';
import pianoSound from '../assets/sounds/piano.wav';
import snareSound from '../assets/sounds/snare.wav';

const testSounds: TestSound[] = [
  { label: 'Click', type: 'sample', path: clickSound },
  { label: 'Guitar', type: 'sample', path: guitarSound },
  { label: 'Piano', type: 'sample', path: pianoSound },
  { label: 'Snare', type: 'sample', path: snareSound },
];

const ConvolverPlayer: React.FC<ConvolverPlayerProps> = ({ irFilePath, audioContext: propAudioContext }) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const convolverProcessorRef = useRef<ConvolverProcessor | null>(null);
  const localAudioContextRef = useRef<AudioContext | null>(null);
  const [irBuffer, setIrBuffer] = useState<AudioBuffer | null>(null);
  const [irInfo, setIrInfo] = useState<string>('');
  const [wetDryMix, setWetDryMix] = useState<number>(0.5);
  const [isAudioContextReady, setIsAudioContextReady] = useState<boolean>(false);

  const getAudioContext = useCallback(() => {
    if (propAudioContext) {
      return propAudioContext;
    }
    if (!localAudioContextRef.current) {
      localAudioContextRef.current = new (window.AudioContext || window.webkitAudioContext)();
    }
    return localAudioContextRef.current;
  }, [propAudioContext]);

  const initializeAudio = useCallback(async () => {
    const audioContext: AudioContext = getAudioContext();
    if (!audioContext) return;


    setIsAudioContextReady(true);

  }, [getAudioContext]);

  useEffect(() => {
    initializeAudio();
    return () => {
      if (localAudioContextRef.current) {
        localAudioContextRef.current.close();
        localAudioContextRef.current = null;
      }
    };
  }, [initializeAudio]);

  // New useEffect for ConvolverProcessor instantiation and updates
  useEffect(() => {
    const audioContext = getAudioContext(); // Get the audio context here
    if (audioContext && irBuffer) {
      if (!convolverProcessorRef.current) {
        convolverProcessorRef.current = new ConvolverProcessor({
          audioContext: audioContext,
          irBuffer: irBuffer,
          wetGainValue: wetDryMix,
        });
      } else {
        convolverProcessorRef.current.updateIrBuffer(irBuffer);
      }
      convolverProcessorRef.current.setWetDryMix(wetDryMix);
    }

    return () => {
      if (convolverProcessorRef.current) {
        convolverProcessorRef.current.dispose();
        convolverProcessorRef.current = null;
      }
    };
  }, [irBuffer, wetDryMix]); // Dependencies for this effect

  useEffect(() => {
    const currentAudioContext = getAudioContext(); // Get the audio context here

    const loadIr = async () => {
      if (!currentAudioContext || !irFilePath) {
        setIrBuffer(null);
        setIrInfo('');
        if (canvasRef.current) {
          const ctx = setupCanvasContext(canvasRef.current);
          if (ctx) {
            ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);
          }
        }
        return;
      }

      try {
        const buffer = await loadAudioBuffer(currentAudioContext, irFilePath);
        setIrBuffer(buffer);
        setIrInfo(`Duration: ${buffer.duration.toFixed(2)}s, Sample Rate: ${buffer.sampleRate}Hz, Channels: ${buffer.numberOfChannels}`);
        convolverProcessorRef.current?.updateIrBuffer(buffer);
        if (canvasRef.current) {
          const color = getAccentColor(canvasRef.current || document.body);
          const ctx = setupCanvasContext(canvasRef.current);
          if (ctx) {
            drawWaveform(ctx, buffer, ctx.canvas.width, ctx.canvas.height, color);
          }
        }
      } catch (error) {
        console.error('Error loading IR file:', error);
        setIrBuffer(null);
        setIrInfo('Error loading IR');
      }
    };

    loadIr();
  }, [irFilePath, getAudioContext]);

  const playTestSound = useCallback(async (soundPath: string) => {
    const audioContext = getAudioContext();
    // Resume AudioContext if suspended, as this is a user gesture
    if (audioContext.state === 'suspended') {
      await audioContext.resume();
    }
    if (!audioContext || !convolverProcessorRef.current || !irBuffer) {
      console.warn('AudioContext, ConvolverProcessor, or IR buffer not ready.');
      return;
    }
    try {
      const soundBuffer = await loadAudioBuffer(audioContext, soundPath);
      convolverProcessorRef.current.play(soundBuffer);
    } catch (error) {
      console.error('Error playing test sound:', error);
    }
  }, [getAudioContext, irBuffer]);

  const handleWetDryMixChange = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    const mix = parseFloat(event.target.value);
    setWetDryMix(mix);
    convolverProcessorRef.current?.setWetDryMix(mix);
  }, []);

  return (
    <div className="convolver-player">
      <div className="convolver-examples">
        {testSounds.map((sound) => (
          <button
            key={sound.label}
            onClick={() => playTestSound(sound.path)}
            disabled={!isAudioContextReady || !irBuffer}
          >
            Play {sound.label}
          </button>
        ))}
      </div>
      <div className="convolver-ir">
        <span className="convolver-ir-info">
          {irInfo}
        </span>
        <canvas ref={canvasRef} width="300" height="150" className="convolver-waveform-canvas"></canvas>
        <div className="convolver-controls">
          <label htmlFor="wetDryMix">Wet/Dry Mix:</label>
          <input
            type="range"
            id="wetDryMix"
            min="0"
            max="1"
            step="0.01"
            value={wetDryMix}
            onChange={handleWetDryMixChange}
          />
          <span>{(wetDryMix * 100).toFixed(0)}% Wet</span>
        </div>
      </div>
    </div>
  );
};

export default ConvolverPlayer;
